### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by TOM-tym** [GLAMOR-USC/CLiMB#2]
Hi, thanks for your awesome work!
I am trying to reimplement the vlit-adapter.
But I am a little bit confused about the requirements.
In [requirements.txt](https://github.com/GLAMOR-USC/CLiMB/blob/main/requirements.txt#L4), the package `transformers==4.16.2` is commented out.
After install  `transformers==4.16.2` manually, I still got an error:
```
       Traceback (most recent call last):
       ...
       from transformers.adapters import AdapterConfig
ModuleNotFoundError: No module named 'transformers.adapters'
```
I also tried to install [adapter-transformers](https://github.com/adapter-hub/adapter-transformers).
But the error still occurs:
```
Traceback (most recent call last):
  ...
AttributeError: 'ViltModel' object has no attribute 'add_adapter'
```
Could your please offer the packages used and update them to the requirements.txt?
Thanks and looking forward to your reply.

**Comment by TOM-tym** [comment]
It turns out that I miss the modified module `adapter-transformers` in the `src` folder.
The `--recurse-submodules` parameter of  git command `git clone https://github.com/GLAMOR-USC/CLiMB.git --recurse-submodules
` is necessary.

**Comment by tejas1995** [comment]
Hi, yes you don't have to install transformers from the requirements file, which is why it is commented out. Instead installing adapter-transformers from within the src directory will install transformers for you.

**Comment by TOM-tym** [comment]
Thanks for your reply!
